### ISSUE TITLE
In case of package pattern conflict file should go to most specific match

### ISSUE THREAD

**Issue by ReillyBrogan** [serpent-os/boulder#31]
```
packages    :
    - "%(name)-devel":
        paths:
            - /usr/bin/ldns-config
            - /usr/share/man/man1/ldns-config.1
            - /usr/share/man/man3
    - "%(name)-utils":
        paths:
            - /usr/bin/*
            - /usr/share/man/man1
```
In this case `/usr/bin/ldns-config` ends up in the `-utils` package when it should be in `-devel`. This is clearly not ideal and the pattern match should work in that the more specific pattern should get the file (even if this is simply evaluated by length of the pattern string, EG `/usr/bin/ldns-config` is longer than `/usr/bin/*` and should therefore get the file)
